---
title: "Interval Estimation"
subtitle: "Lecture Demo"
date: "December 7th, 2023"
format: revealjs
---

## Checklist

Before class starts, I pull up a checklist of information that students may reference to help best situate them in and outside of class. Items often include:

-- Be checking Slack 

-- Clone the in-class activity from GitHub 

-- Due Dates 

## Warm Up Questions 

-- Typically between 1-3 questions 

-- Provide students a "no stakes" assessment on previous material 

-- Students are encouraged to work alone, or in a group setting 

## Example Warm Up: Notation 

Population vs Sample

-- What the difference?

-- How does notation change for the following:

--- Mean

--- Proportion

--- Slope

## Example Warm Up

-- When do we create confidence intervals? 

-- When do we conduct a hypothesis test?

# Confidence Intervals

## Confidence Intervals

-- are a range of **plausible values** that our population parameter could be

-- we make confidence intervals when we want to ESTIMATE

## Confidence Intervals

By the end of class, we will

-- know how to calculate confidence intervals using bootstrap methods for difference in means

-- understand what bootstrap methods are

-- understand how the level of confidence influences our confidence interval

-- understand how to interpret a confidence interval in the context of the problem

## ae-demo

## Wrap Up

What are bootstrap methods? 

- Resampling **with replacmement* from your own data to create a bootstrap distribution! 

## Wrap Up 

How did we create a confidence interval using bootstrap methods for a difference in means?

- Create a simulated distribution of sample statistics, and found quantiles specific to the level of confidence we wanted!

## Wrap Up

How does the level of confidence impact the center and width of our confidence intervals?

- Center?

- Width?

## Wrap Up

How do we interpret confidence intervals?

- We are __% confident that the true population parameter is between (#,#). Note the order of subtraction, and how that changes our interpretation!
